In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("sales_data_sample.csv", encoding="latin1")

In [5]:
df.head()
df.head(2)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.0,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.9,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small

In [6]:
df.tail()
df.tail(2)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [7]:
df.sample()
df.sample(2)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
356,10276,38,83.79,4,3184.02,8/2/2004 0:00,Shipped,3,8,2004,...,7635 Spinnaker Dr.,NaN,Brickhaven,MA,58339,USA,NaN,Barajas,Miguel,Medium
2586,10401,85,88.75,10,7543.75,4/3/2005 0:00,On Hold,2,4,2005,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Large

In [8]:
df.size

df.shape
df.shape[0]
df.shape[1]

25

In [9]:
df.columns
df.columns.tolist()

['ORDERNUMBER',
 'QUANTITYORDERED',
 'PRICEEACH',
 'ORDERLINENUMBER',
 'SALES',
 'ORDERDATE',
 'STATUS',
 'QTR_ID',
 'MONTH_ID',
 'YEAR_ID',
 'PRODUCTLINE',
 'MSRP',
 'PRODUCTCODE',
 'CUSTOMERNAME',
 'PHONE',
 'ADDRESSLINE1',
 'ADDRESSLINE2',
 'CITY',
 'STATE',
 'POSTALCODE',
 'COUNTRY',
 'TERRITORY',
 'CONTACTLASTNAME',
 'CONTACTFIRSTNAME',
 'DEALSIZE']

In [10]:
df.index

RangeIndex(start=0, stop=2823, step=1)

In [11]:
df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
ADDRESSLINE2         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

In [12]:
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB

In [14]:
df.nunique()

df.value_counts("SALES")
df["SALES"].value_counts()

SALES
3003.00    3
5464.69    2
2257.92    2
5004.80    2
2172.48    2
          ..
2312.24    1
2793.71    1
1908.28    1
3441.37    1
2116.16    1
Name: count, Length: 2763, dtype: int64

In [15]:

df["SALES"] #select one column

df[["SALES", "COUNTRY", "QUANTITYORDERED"]] # Selecting multiple columns

df.iloc[2] #integer position
df.iloc[0:2]

df.loc[12] #Label based indexing
df.loc[0:10]
df.loc[:, "SALES"]

df["SALES"] > 5000

df[df["SALES"] > 5000]
df[(df["SALES"] > 5000) & (df["QUANTITYORDERED"] >20) ]
df[(df["SALES"] > 5000) | (df["QUANTITYORDERED"] >20) ]

df[ df["PRODUCTLINE"].isin(["Classic Cars", "Motorcycles"])]

df.query("SALES > 5000 ")
df.query("SALES > 5000 and QUANTITYORDERED > 20")

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
4,10159,49,100.0,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
7,10188,48,100.0,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
20,10341,41,100.0,9,7737.93,11/24/2004 0:00,Shipped,4,11,2004,...,Geislweg 14,NaN,Salzburg,NaN,5020,Austria,EMEA,Pipps,Georg,Large
25,10417,66,100.0,2,7516.08,5/13/2005 0:00,Disputed,2,5,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Large
26,10103,26,100.0,11,5404.62,1/29/2003 0:00,Shipped,1,1,2003,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2685,10361,44,100.0,10,5001.92,12/17/2004 0:00,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Medium
2686,10375,44,100.0,11,5208.72,2/3/2005 0:00,Shipped,1,2,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
2689,10401,77,92.0,9,7084.00,4/3/2005 0:00,On Hold,2,4,2005,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Large
2715,10397,48,100.0,3,5192.64,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Medium
2820,10386,43,100.0,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium

In [16]:
# Chapter 5 DATA CLEANING

df.isna()
df.isnull()
df.isna().sum()
df.isnull().sum()
df.notna()
df.notna().sum()


df.duplicated()
df.duplicated().sum()

df[["ORDERNUMBER", "ORDERLINENUMBER"]].duplicated().sum()

np.int64(0)

In [17]:
df.columns.tolist()
df["ADDRESSLINE2"].isna().sum()
df["ADDRESSLINE2"].isna().sum()
df["TERRITORY"].isna().sum()

np.int64(1074)

In [18]:

df = df.drop(columns=["TERRITORY"])

#OR 

df.drop(columns=["ADDRESSLINE2"], inplace=True)

In [19]:
df.columns.tolist()

['ORDERNUMBER',
 'QUANTITYORDERED',
 'PRICEEACH',
 'ORDERLINENUMBER',
 'SALES',
 'ORDERDATE',
 'STATUS',
 'QTR_ID',
 'MONTH_ID',
 'YEAR_ID',
 'PRODUCTLINE',
 'MSRP',
 'PRODUCTCODE',
 'CUSTOMERNAME',
 'PHONE',
 'ADDRESSLINE1',
 'CITY',
 'STATE',
 'POSTALCODE',
 'COUNTRY',
 'CONTACTLASTNAME',
 'CONTACTFIRSTNAME',
 'DEALSIZE']

In [20]:
# Filling missing values

# df.info()
df["STATE"].isna().sum()

df["STATE"] = df["STATE"].fillna("Unknown")

In [21]:
df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

In [22]:
df["POSTALCODE"].isna().sum()

df["POSTALCODE"] = df["POSTALCODE"].fillna("Unknown")

In [23]:
#ORDER DATE is of object type we have to convert it into date

df["ORDERDATE"]

df["ORDERDATE"] = pd.to_datetime(df["ORDERDATE"])

df["ORDERDATE"].dt.year
df["ORDERDATE"].dt.month
df["ORDERDATE"].dt.date
df["ORDERDATE"].dt.day
df["ORDERDATE"].dtypes

dtype('<M8[ns]')

In [24]:
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[ns]
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  CITY              2823 non-null   object
 17  STATE             2823 non-null   object
 18  POSTALCODE        2823 non-null   object
 19  COUNTRY           2823 non-null   object
 20  CONTACTLASTNAME   2823 non-null   object
 21  CONTACTFIRSTNAME  2823 non-null   object
 22  DEALSIZE          2823 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(7), object(13)
memory usage: 507.4+ KB

In [60]:
# GroupBy and Aggregation

#Average Sales for each country
df.groupby("COUNTRY")["SALES"].mean() 

#Total Sales for each country
df.groupby("COUNTRY")["SALES"].sum()
df.groupby("COUNTRY")["SALES"].min()
df.groupby("COUNTRY")["SALES"].max()
df.groupby("COUNTRY")["SALES"].count()


#Multiple Aggregation

df.groupby("COUNTRY")["SALES"].agg(["mean", "max", "min", "sum"])

df.groupby("COUNTRY").agg(
    avg_sales=("SALES", "mean"),
    sum_sales=("SALES", "sum"),
    min_sales=("SALES", "min"),
    max_sales=("SALES", "max")
)

df.groupby("COUNTRY", as_index= False)["SALES"].mean()

        COUNTRY        SALES
0     Australia  3408.773514
1       Austria  3673.864182
2       Belgium  3285.230909
3        Canada  3201.122286
4       Denmark  3899.002381
5       Finland  3582.412065
6        France  3537.950701
7       Germany  3556.001452
8       Ireland  3609.776875
9         Italy  3315.701858
10        Japan  3618.611731
11       Norway  3617.220000
12  Philippines  3615.989615
13    Singapore  3651.752025
14        Spain  3554.640117
15       Sweden  3684.459825
16  Switzerland  3797.211613
17           UK  3325.558750
18          USA  3613.528715

In [26]:
df.duplicated().sum()
df.duplicated(subset=["ORDERNUMBER", "ORDERLINENUMBER"]).sum()

np.int64(0)

In [27]:

df["STATUS"].nunique()
df["PRODUCTLINE"].nunique()
df["CITY"].nunique()
df["STATE"].nunique()

17

In [28]:
# for all categories

categorical_cols = df.select_dtypes(include="object").columns

# categorical_cols

for col in categorical_cols:
    print("\n", col)
    print(df[col].nunique())
    print(df[col].unique()[:10])

 STATUS
6
['Shipped' 'Disputed' 'In Process' 'Cancelled' 'On Hold' 'Resolved']

 PRODUCTLINE
7
['Motorcycles' 'Classic Cars' 'Trucks and Buses' 'Vintage Cars' 'Planes'
 'Ships' 'Trains']

 PRODUCTCODE
109
['S10_1678' 'S10_1949' 'S10_2016' 'S10_4698' 'S10_4757' 'S10_4962'
 'S12_1099' 'S12_1108' 'S12_1666' 'S12_2823']

 CUSTOMERNAME
92
['Land of Toys Inc.' 'Reims Collectables' 'Lyon Souveniers'
 'Toys4GrownUps.com' 'Corporate Gift Ideas Co.' 'Technics Stores Inc.'
 'Daedalus Designs Imports' 'Herkku Gifts' 'Mini Wheels Co.'
 'Auto Canal Petit']

 PHONE
91
['2125557818' '26.47.1555' '+33 1 46 62 7555' '6265557265' '6505551386'
 '6505556809' '20.16.1555' '+47 2267 3215' '6505555787' '(1) 47.55.6555']

 ADDRESSLINE1
92
['897 Long Airport Avenue' "59 rue de l'Abbaye"
 '27 rue du Colonel Pierre Avia' '78934 Hillside Dr.' '7734 Strong St.'
 '9408 Furth Circle' '184, chausse de Tournai'
 'Drammen 121, PR 744 Sentrum' '5557 North Pendale Street'
 '25, rue Lauriston']

 CITY
73
['NYC' 'Reims' 'Paris' 'Pasadena' 'San Francisco' 'Burlingame' 'Lille'
 'Bergen' 'Melbourne' 'Newark']

 STATE
17
['NY' 'Unknown' 'CA' 'Victoria' 'NJ' 'CT' 'MA' 'PA' 'NSW' 'Queensland']

 POSTALCODE
74
['10022' '51100' '75508' '90003' 'Unknown' '94217' '59000' 'N 5804'
 '75016' '3004']

 COUNTRY
19
['USA' 'France' 'Norway' 'Australia' 'Finland' 'Austria' 'UK' 'Spain'
 'Sweden' 'Singapore']

 CONTACTLASTNAME
77
['Yu' 'Henriot' 'Da Cunha' 'Young' 'Brown' 'Hirano' 'Rance' 'Oeztan'
 'Murphy' 'Perrier']

 CONTACTFIRSTNAME
72
['Kwai' 'Paul' 'Daniel' 'Julie' 'Juri' 'Martine' 'Veysel' 'Dominique'
 'Peter' 'Michael']

 DEALSIZE
3
['Small' 'Medium' 'Large']

In [29]:
#Frequency of categorical values

df["PRODUCTLINE"].value_counts()

PRODUCTLINE
Classic Cars        967
Vintage Cars        607
Motorcycles         331
Planes              306
Trucks and Buses    301
Ships               234
Trains               77
Name: count, dtype: int64

In [30]:
df["STATUS"].value_counts()

STATUS
Shipped       2617
Cancelled       60
Resolved        47
On Hold         44
In Process      41
Disputed        14
Name: count, dtype: int64

In [31]:
df["DEALSIZE"].value_counts()

DEALSIZE
Medium    1384
Small     1282
Large      157
Name: count, dtype: int64

In [32]:
df["COUNTRY"].value_counts()

COUNTRY
USA            1004
Spain           342
France          314
Australia       185
UK              144
Italy           113
Finland          92
Norway           85
Singapore        79
Canada           70
Denmark          63
Germany          62
Sweden           57
Austria          55
Japan            52
Belgium          33
Switzerland      31
Philippines      26
Ireland          16
Name: count, dtype: int64

In [33]:
# Descriptive statistics
df.describe()

df[["QUANTITYORDERED", "PRICEEACH", "SALES", "MSRP"]].describe()

       QUANTITYORDERED    PRICEEACH         SALES         MSRP
count      2823.000000  2823.000000   2823.000000  2823.000000
mean         35.092809    83.658544   3553.889072   100.715551
std           9.741443    20.174277   1841.865106    40.187912
min           6.000000    26.880000    482.130000    33.000000
25%          27.000000    68.860000   2203.430000    68.000000
50%          35.000000    95.700000   3184.800000    99.000000
75%          43.000000   100.000000   4508.000000   124.000000
max          97.000000   100.000000  14082.800000   214.000000

In [34]:
#Analysze individual numerical columns

df["SALES"].mean()
df["SALES"].median()
df["SALES"].max()
df["SALES"].min()
df["SALES"].std()

1841.8651057401805

In [35]:
#Check outliers using IQR

Q1 = df["SALES"].quantile(0.25)
Q3 = df["SALES"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["SALES"] < lower_bound) |
    (df["SALES"] > upper_bound)
]

In [36]:
len(outliers)

81

In [37]:
#Checking outliers for other numerical columns

numeric_cols =["QUANTITYORDERED", "PRICEEACH", "SALES", "MSRP"]

for col in numeric_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)


    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(col ,":", len(outliers) ,"outliers")

QUANTITYORDERED : 8 outliers
PRICEEACH : 0 outliers
SALES : 81 outliers
MSRP : 28 outliers

In [38]:
# Analyze correlation

df[["QUANTITYORDERED", "PRICEEACH", "SALES", "MSRP"]].corr()

                 QUANTITYORDERED  PRICEEACH     SALES      MSRP
QUANTITYORDERED         1.000000   0.005564  0.551426  0.017881
PRICEEACH               0.005564   1.000000  0.657841  0.670625
SALES                   0.551426   0.657841  1.000000  0.635239
MSRP                    0.017881   0.670625  0.635239  1.000000

In [39]:
# Analyze quantity vs sales

df.groupby("QUANTITYORDERED")["SALES"].mean()

QUANTITYORDERED
6       663.390000
10      986.800000
11      808.720000
12     1961.280000
13     1057.290000
15      832.237500
16     1207.680000
18     1500.540000
19     1541.786667
20     2066.372043
21     2091.320680
22     2445.577391
23     2388.899726
24     2424.371868
25     2469.843085
26     2618.728125
27     2907.570600
28     2737.249268
29     3005.529149
30     2818.080000
31     2867.375361
32     3179.832967
33     3418.570435
34     3356.522500
35     3249.015493
36     3688.471011
37     3750.715517
38     3971.179560
39     3675.508571
40     3911.656410
41     4547.225464
42     4133.424474
43     4479.774941
44     4304.653483
45     4486.486082
46     4750.715644
47     5024.951571
48     4750.284468
49     4920.402308
50     5304.753846
51     4557.615000
52     4219.280000
54     6566.670000
55     5551.184375
56     5565.280000
58     7307.420000
59     6012.296667
60     7291.800000
61     4895.250000
62     4819.260000
64     5360.213333
65    10468.900000
66     7721.472000
70     8869.000000
76    11001.500000
77     7084.000000
85     7543.750000
97     9048.160000
Name: SALES, dtype: float64

In [59]:
#Productline analysis

product_sales = df.groupby("PRODUCTLINE")["SALES"].sum()

product_sales.sort_index(ascending=False)

df.groupby("PRODUCTLINE")["SALES"].mean()
df["PRODUCTLINE"].value_counts()

PRODUCTLINE
Classic Cars        967
Vintage Cars        607
Motorcycles         331
Planes              306
Trucks and Buses    301
Ships               234
Trains               77
Name: count, dtype: int64

In [40]:
#Country analysis

df.groupby("DEALSIZE")["SALES"].sum()
df.groupby("DEALSIZE")["SALES"].mean()
df["DEALSIZE"].value_counts()

DEALSIZE
Medium    1384
Small     1282
Large      157
Name: count, dtype: int64

In [41]:
# Date analysis

df["ORDER_YEAR"] = df["ORDERDATE"].dt.year
df["ORDER_MONTH"] = df["ORDERDATE"].dt.month
df["ORDER_QUARTER"] = df["ORDERDATE"].dt.quarter

In [42]:
# Yearly sales

yearly_sales =  df.groupby("ORDER_YEAR")["SALES"].sum()

yearly_sales.sort_index()

ORDER_YEAR
2003    3516979.54
2004    4724162.60
2005    1791486.71
Name: SALES, dtype: float64

In [43]:
# Monthly sales

monthly_sales = df.groupby("ORDER_MONTH")["SALES"].sum() 
monthly_sales.sort_index()

ORDER_MONTH
1      785874.44
2      810441.90
3      754501.39
4      669390.96
5      923972.56
6      454756.78
7      514875.97
8      659310.57
9      584724.27
10    1121215.22
11    2118885.67
12     634679.12
Name: SALES, dtype: float64

In [44]:
#Quarterly sales

quarterly_sales = df.groupby("ORDER_QUARTER")["SALES"].sum()
quarterly_sales.sort_index()

ORDER_QUARTER
1    2350817.73
2    2048120.30
3    1758910.81
4    3874780.01
Name: SALES, dtype: float64

In [45]:
#Year + month sales

year_month_sales = df.groupby(
    ["ORDER_YEAR", "ORDER_MONTH"]
)["SALES"].sum()

year_month_sales.sort_index()

ORDER_YEAR  ORDER_MONTH
2003        1               129753.60
            2               140836.19
            3               174504.90
            4               201609.55
            5               192673.11
            6               168082.56
            7               187731.88
            8               197809.30
            9               263973.36
            10              568290.97
            11             1029837.66
            12              261876.46
2004        1               316577.42
            2               311419.53
            3               205733.73
            4               206148.12
            5               273438.39
            6               286674.22
            7               327144.09
            8               461501.27
            9               320750.91
            10              552924.25
            11             1089048.01
            12              372802.66
2005        1               339543.42
            2               358186.18
            3               374262.76
            4               261633.29
            5               457861.06
Name: SALES, dtype: float64

In [46]:
# Customer Analysis

customer_sales = df.groupby("CUSTOMERNAME")["SALES"].sum()
customer_sales.sort_index(ascending=False)

df["CUSTOMERNAME"].value_counts()

CUSTOMERNAME
Euro Shopping Channel           259
Mini Gifts Distributors Ltd.    180
Australian Collectors, Co.       55
La Rochelle Gifts                53
AV Stores, Co.                   51
                               ...
Microscale Inc.                  10
Royale Belge                      8
Auto-Moto Classics Inc.           8
Atelier graphique                 7
Boards & Toys Co.                 3
Name: count, Length: 92, dtype: int64

In [49]:
#Product Line + dael_size
df.groupby(
    ["PRODUCTLINE", "DEALSIZE"]
)["SALES"].sum()

PRODUCTLINE       DEALSIZE
Classic Cars      Large        796641.79
                  Medium      2430258.39
                  Small        692715.48
Motorcycles       Large        159144.61
                  Medium       680369.69
                  Small        326874.04
Planes            Large         72031.70
                  Medium       538606.05
                  Small        364365.82
Ships             Medium       422735.07
                  Small        291702.06
Trains            Large          8977.05
                  Medium       112895.40
                  Small        104371.02
Trucks and Buses  Large         56256.06
                  Medium       817027.68
                  Small        254506.10
Vintage Cars      Large        209068.05
                  Medium      1085539.96
                  Small        608542.83
Name: SALES, dtype: float64

In [50]:
# ProductLine + year

df.groupby(
    ["PRODUCTLINE", "ORDER_YEAR"]
)["SALES"].sum()

PRODUCTLINE       ORDER_YEAR
Classic Cars      2003          1484785.29
                  2004          1762257.09
                  2005           672573.28
Motorcycles       2003           370895.58
                  2004           560545.23
                  2005           234947.53
Planes            2003           272257.60
                  2004           502671.80
                  2005           200074.17
Ships             2003           244821.09
                  2004           341437.97
                  2005           128178.07
Trains            2003            72802.29
                  2004           116523.85
                  2005            36917.33
Trucks and Buses  2003           420429.93
                  2004           529302.89
                  2005           178057.02
Vintage Cars      2003           650987.76
                  2004           911423.77
                  2005           340739.31
Name: SALES, dtype: float64

In [68]:
#Final check

df.shape

(2823, 26)

In [52]:
df.dtypes

ORDERNUMBER                  int64
QUANTITYORDERED              int64
PRICEEACH                  float64
ORDERLINENUMBER              int64
SALES                      float64
ORDERDATE           datetime64[ns]
STATUS                      object
QTR_ID                       int64
MONTH_ID                     int64
YEAR_ID                      int64
PRODUCTLINE                 object
MSRP                         int64
PRODUCTCODE                 object
CUSTOMERNAME                object
PHONE                       object
ADDRESSLINE1                object
CITY                        object
STATE                       object
POSTALCODE                  object
COUNTRY                     object
CONTACTLASTNAME             object
CONTACTFIRSTNAME            object
DEALSIZE                    object
ORDER_YEAR                   int32
ORDER_MONTH                  int32
ORDER_QUARTER                int32
dtype: object

In [53]:
df.isnull().sum()

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
ORDER_YEAR          0
ORDER_MONTH         0
ORDER_QUARTER       0
dtype: int64

In [65]:
df.duplicated().sum()

np.int64(0)

In [67]:
df.to_csv("cleaned_dataset.csv", index=False)

In [69]:
cleaned_df = pd.read_csv("cleaned_dataset.csv")

In [71]:
cleaned_df.head()
cleaned_df.shape
cleaned_df.columns

(2823, 26)